### ISSUE TITLE
Two DGs

### ISSUE THREAD

**Issue by damithc** [AY1920S2-CS2113T-T12-1/tp#202]
There are two DGs for your team in LumiNUS.
We'll be taking the newer file [CS2113T-T12-1][WhenFree]DG(CHAN HONG YI, M).pdf unless we hear from you otherwise.

**Comment by MeLoveCarbs** [comment]
Hi Prof, theres a miscommunication and both of us uploaded the same DG, both are the same

**Comment by damithc** [comment]
Noted guys.
