### ISSUE TITLE
add CommandClass to handle all Commands

### ISSUE THREAD

**Issue by lowxizhi** [AY1920S2-CS2113T-T12-1/tp#46]

**Comment by lowxizhi** [comment]
#84 
done except for "add using link" command

**Comment by MeLoveCarbs** [comment]
Fixed 'add user link', closing issue

**Comment by lowxizhi** [comment]
We are currently passing the reference of private instance variables of our main class ```MeetingOrganizer``` into methods of another class ```Command```, in order to modify the private instance variables. However, this doesnt seem to be a good idea (refer to mistake #3 in https://dzone.com/articles/java-getter-and-setter-basics-common-mistakes-and), as we are modifying a private instance variable directly, outside of its class.

The right way modify a private instance variable is to use both getter and setter.  In the **getter**, return a copy of the private instance variable. In the **setter**, copy the passed values to the private instance variable. 

However in this case where it does not make sense to create ```MeetingOrganizer``` object in the ```Command``` class, we cannot use getter and setter in the ```Command``` class. Hence we are passing the reference of the private instance variables. 

Is there a better way? Or perhaps we shouldn't have a separate ```Command``` class that modifies the private instance variables of the main class ```MeetingOrganizer```?

**Comment by damithc** [comment]
> We are currently passing the reference of private instance variables of our main class `MeetingOrganizer` into methods of another class `Command`, in order to modify the private instance variables. However, this doesnt seem to be a good idea (refer to mistake #3 in https://dzone.com/articles/java-getter-and-setter-basics-common-mistakes-and), as we are modifying a private instance variable directly, outside of its class.
> 
> The right way modify a private instance variable is to use both getter and setter. In the **getter**, return a copy of the private instance variable. In the **setter**, copy the passed values to the private instance variable.
> 
> However in this case where it does not make sense to create `MeetingOrganizer` object in the `Command` class, we cannot use getter and setter in the `Command` class. Hence we are passing the reference of the private instance variables.
> 
> Is there a better way? Or perhaps we shouldn't have a separate `Command` class that modifies the private instance variables of the main class `MeetingOrganizer`?

@lowxizhi I can't give a more concrete answer without reading some of the code. But in general, given the nature of this project, it is fine to use even less-than-ideal designs if,
1. moving to a better design would take a lot of extra effort
1. you are aware of the problem and alternatives

You can document these cases in your DG i.e., current design, alternatives, pros and cons of each, reason for the current choice (point 1 above is a valid reason)
