### ISSUE TITLE
Edit function for existing contacts' (including mainuser) schedules. Allow blocking and freeing of slots.

### ISSUE THREAD

**Issue by lowxizhi** [AY1920S2-CS2113T-T12-1/tp#67]

**Comment by MeLoveCarbs** [comment]
Would this be implemented within the TeamMember class. Meaning its an ArrayList of Meetings within the class representing the blocked slots of that particular TeamMember object

**Comment by lowxizhi** [comment]
I didnt save the name of the blocked slots in an ArrayList. I modified the teammember's schedule directly. Similar to the previous addBusyBlocks() method.

**Comment by lowxizhi** [comment]
#68
