### ISSUE TITLE
Did the publish the docs folder?

### ISSUE THREAD

**Issue by damithc** [AY1920S2-CS2113T-T12-1/tp#80]
Check if you published the correct folder for gh-pages. You were supposed to publish the `docs` folder.
See below:

![image](https://user-images.githubusercontent.com/1673303/77826094-60923500-7148-11ea-94f4-57b2bf18d005.png)

**Comment by matthewc97** [comment]
Hi Prof, I have resolved the issue. The source was set to the master branch instead of master/docs.

Sorry for the inconvenience caused.

**Comment by damithc** [comment]
Nice. Closing.
